---
title: "test_dashboard_1"
output: 
  flexdashboard::flex_dashboard:
    orientation: row
    vertical_layout: fill
    social: ["menu"]
    source_code: "embed"
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(here)
library(igraph)
library(ggraph)
library(tidygraph)
library(writexl)

read_csv("DATA/ORCIDS W1 SP21 RAW.csv") -> DBdata
select(DBdata, 3,8:13) -> DBdata_1 #MessageID, Forum Name, Parent Post/InReplyTo, ThreadID, AuthorFrom
select(DBdata_1, 1,5) -> messageID #MessageID, AuthorFrom
na.omit(DBdata_1) -> DBdata_2 #Removes initial
select(DBdata_2, 2:5) -> DBdata_3 #Forum Name, Parent Post/InReplyTo, ThreadID, AuthorFrom
  colnames(DBdata_3)[2] <- c("MessageID") #change InReplyTo to message ID
  colnames(DBdata_3)[4] <- c("AuthorFrom") 
inner_join(messageID, DBdata_3, by = "MessageID") -> DBdata_4
colnames(DBdata_4)[2] <- c("AuthorTo")
DBdata_4[c(3,5,2,1,4)] -> DBdata_5
DBdata_5[order(DBdata_5$"ForumName"),] -> DBdata_6
select(DBdata_6, 2,3) -> DBdata_6
gr1 <- graph_from_data_frame(DBdata_6, directed = TRUE)

```


sidebar {.sidebar}
-----------------------------------------------------------------------

### Network Graphs


 

Column {.tabset}
-----------------------------------------------------------------------

### Chart A

```{r}
graph <- create_notable('zachary')
ggraph(gr1, 'matrix', sort.by = node_rank_leafsort()) + 
  geom_edge_point(mirror = TRUE) + 
  coord_fixed()
```

### Chart B

```{r}
GrLayout = create_layout(gr1, layout='eigen')

  ggraph(GrLayout) +
  geom_edge_link() +
  # geom_node_point(aes(size = coreness)) +
  theme(legend.position="bottom")
```

### Chart C

```{r}

```

